service:
  name: auction-service

plugins:
# allows you to bundle your application using webpack and ECMA script 6+
  - serverless-bundle
# allows you to interpolate AWS parameters(region, accountID)
  - serverless-pseudo-parameters

# about the account provider
provider:
  name: aws
  runtime: nodejs12.x
# how much memory our lambda function will get when executed (set globally instead of per function)
  memorySize: 256
# set custom options for development, if no stage provided
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable
  
resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH


# define lambda function with handler and event trigger
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  bundle:
    linting: true